export const products = [
  {//Placeholders for absent images
    id: 1,
    name: 'Wireless Headphone',
    category: 'Accesories',
    href: '#', 
    imageSrc: 'https://placehold.co/400x300/e0f2fe/0369a1?text=Headphones', 
    imageAlt: 'Wireless, Bluetooth, built-in mic, electroacoustic transducers.',
    price: '$100.00',
  },
  {
    id: 2,
    name: 'Smart Watch',
    category: 'Accesories',
    href: '#',
    imageSrc: 'https://placehold.co/400x300/ffe4e6/be185d?text=Smart+Watch', 
    imageAlt: 'Health monitoring, fitness tracker, GPS, online payments.',
    price: '$499.00',
  },
  {
    id: 3,
    name: 'Charger',
    category: 'Accesories',
    href: '#',
    imageSrc: 'https://placehold.co/400x300/dcfce7/16a34a?text=Powerbank', 
    imageAlt: 'High-power, c-type charger.',
    price: '$49.00',
  },
  {
    id: 4,
    name: 'Laptop',
    category: 'Computers',
    href: '#',
    imageSrc: 'https://placehold.co/400x300/fefce8/ca8a04?text=Laptop', 
    imageAlt: 'Laptop for office works and designers.',
    price: '$749.00',
  },
  {
    id: 5,
    name: 'Webcam',
    category: 'Cameras',
    href: '#',
    imageSrc: 'https://placehold.co/400x300/f0f9ff/0c4a6e?text=Webcam', 
    imageAlt: 'Full HD.',
    price: '$99.00',
  },
  {
    id: 6,
    name: 'Game Mouse',
    category: 'Accesories',
    href: '#',
    imageSrc: 'https://placehold.co/400x300/f3e8ff/7e22ce?text=Game+Mouse',
    imageAlt: 'Adjustable DPI and sensible mouse with RGB lighting.',
    price: '$49.00',
  },
];
